
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaiwupnajneswpbpkrlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaXd1cG5ham5lc3dwYnBrcmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Mzc1NDIsImV4cCI6MjA2MjExMzU0Mn0.jtYneqkIoVbQQpQi0lEKUy2jbTV2MSzeWM1HGL9Lu34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});
